#--- StorageBroker StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-broker
  labels:
    app: storage-broker
spec:
  selector:
    matchLabels:
      app: storage-broker
  serviceName: "storage-broker"
  replicas: 1
  template:
    metadata:
      labels:
        app: storage-broker
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: storage-broker
          image: neondatabase/neon:3000
          command:
            - "storage_broker"
            - "--listen-addr=0.0.0.0:50051"
          ports:
            - containerPort: 50051
              protocol: TCP
      restartPolicy: Always
---
#--- StorageBroker Service
apiVersion: v1
kind: Service
metadata:
  name: storage-broker
  labels:
    app: storage-broker
spec:
  ports:
    - name: "50051"
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: storage-broker
